
#Persistent Volume (PV)

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk:
    pdName: my-disk-123
    fsType: ext4
