
#redis-master-deployment.yaml

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend


# NOTE: if your cluster doesn't support LB, use type as NP
# type: NodePort
