

#pvc-dv1.yml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-disk-claim-1
spec:
  resources:
   requests:
     storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
